- set_fact: nginx_user="nginx"
  when: ansible_os_family == 'RedHat'
- set_fact: nginx_user="www-data"
  when: ansible_os_family == 'Debian'
- name: Configure nginx.conf
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx
- name: Remove default nginx configurations
  file: state=absent path={{item}}
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/conf.d/default.conf
  notify: restart nginx
