- hosts: nginx
  tasks:
    - command: "curl -s -H 'Host: {{item.0.name}}' 'http://127.0.0.1/{{item.1.name}}'"
      register: curlresponse
      with_subelements: 
        - nginx_sites
        - files
      changed_when: false
    - debug: var=item.stdout
      with_items: curlresponse.results
    - fail: Failed to pull expected example website content
      when: "item.stdout != '<div style=\\'text-align: center\\'>\nExample Website\n</div>'"
      with_items: curlresponse.results
