- hosts: nginx
  tasks:
    - command: "curl -v -H 'Host: testsite' 'http://127.0.0.1:81/up'"
      register: curlresponse
    - assert: 
        that:
          - curlresponse.rc == 0
          - '"200" in curlresponse.stderr'
          - '"happy" in curlresponse.stdout'

    - command: "curl -v -H 'Host: testsite' 'http://127.0.0.1:81/404'"
      register: curlresponse
    - assert: 
        that:
          - curlresponse.rc == 0
          - '"404" in curlresponse.stderr'

    - command: "curl -v -H 'Host: testsite' 'http://127.0.0.1:81/other'"
      register: curlresponse
    - assert: 
        that:
          - curlresponse.rc == 0
          - '"204" in curlresponse.stderr'
