- name: Install nginx PPA
  apt_repository:
    repo: "{{ nginx_ppa_repository }}"
    state: present

- name: Install nginx from PPA
  apt:
    name: "{{ nginx_ppa_version_string }}"
    state: present
    update_cache: yes
    cache_valid_time: 10800
  notify: restart nginx
